### ISSUE TITLE
Expires in 45 Days Report

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#135]
Stella
I ran this report to see how many members expire in 45 days and these are the results i got.
If you scroll through, pricing is wrong, there are dates past the 45 day mark, and towards the end there are expiration dates of 2018. In membership, it says 108 records, but when i print the invoice, the pds file shows 117. 
[Expires in 45 Days report.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/994379/Expires.in.45.Days.report.pdf)
 see attached.

**Comment by kbt1** [comment]
Stella and Sagar
I do not want to invoice 30 day demo users unless there is a fee in amount due. The last page of companies selected are all demo users. Some may have checked out the demo and some have not.
We need CMS system in the new management system.   I cant even tell if they are a web user or desktop user, can you add in a check mark box to show if they are ProWeb or ProDesktop like in CMS on main page of membership?

![image](https://cloud.githubusercontent.com/assets/26387044/26061625/0f2e7d02-394e-11e7-8177-52d95668c03b.png)

**Comment by kbt1** [comment]
i just noticed, the Prosis Pro Demo people come up on the Expires in 45 Days but nothing prints.
So when i pull this, i am not getting an accurate count of how many invoices will print.

**Comment by sagarjagdish** [comment]
@omnitekinc  :  as we discussed on hangout we have implemented checkbox on membership listing screen. So if we want to generate invoice for Membership and Prosis Pro, need to select Membership Only and Prosis Pro Only  and uncheck 30 day's Trial users. It will list only member and posis users.

![image](https://cloud.githubusercontent.com/assets/7322922/26253336/a74e7f58-3cd0-11e7-9907-cb92c5030bee.png)

Also please explain to AERA like why listing page count and invoice page count not match because of 90 days expiry difference will create separate invoice for Membership and Prosis Pro.

**Comment by omnitekinc** [comment]
Karen, please take a look and let me know if this works.

**Comment by kbt1** [comment]
ok, now i understand.
however. i just selected "Expires in 45 days"  all and unselected Prosis Pro 30 Day Trial and still coming up with wrong data. This should only bring up members that expire in 45 days.

![image](https://cloud.githubusercontent.com/assets/26387044/26318473/d00b5d64-3ee0-11e7-804f-78fc7c7731c5.png)

ID#44073 should not be on list. Maybe i am misunderstanding this. 
ID#32925 should not be on list.

**Comment by sagarjagdish** [comment]
We have resolved this issue can you please check and confirm ?

**Comment by kbt1** [comment]
looks good.
