### ISSUE TITLE
Prosis Pro CMS vs Prosis in New Management System

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#136]
Stella
Member #39999 was using desktop and i got him on the web version.
In CMS, made the changes and can view IP address and see he got in.
![image](https://cloud.githubusercontent.com/assets/26387044/26012322/cd0d2fda-3719-11e7-9b3a-0907cac28108.png)image](https://cloud.githubusercontent.com/assets/26387044/26012335/d5431b60-3719-11e7-856d-aa0ccb026198.png)
![image](https://cloud.githubusercontent.com/assets/26387044/26012486/3a40ca12-371a-11e7-8e1b-b35f935a2e0e.png)

I made the appropriate changes in the Management System and when i click on IP address nothing comes up
![image](https://cloud.githubusercontent.com/assets/26387044/26012387/f75dbc5a-3719-11e7-820e-0210f547e83d.png)

is there something different in the management system that has to be done?

**Comment by omnitekinc** [comment]
Will look into this.


On May 12, 2017 at 11:54:40 AM, kbt1 (notifications@github.com) wrote:

Stella
Member #39999 was using desktop and i got him on the web version.
In CMS, made the changes and can view IP address and see he got in.
[image: image]
<https://cloud.githubusercontent.com/assets/26387044/26012322/cd0d2fda-3719-11e7-9b3a-0907cac28108.png>
image](
https://cloud.githubusercontent.com/assets/26387044/26012335/d5431b60-3719-11e7-856d-aa0ccb026198.png
)
[image: image]
<https://cloud.githubusercontent.com/assets/26387044/26012486/3a40ca12-371a-11e7-8e1b-b35f935a2e0e.png>

I made the appropriate changes in the Management System and when i click on
IP address nothing comes up
[image: image]
<https://cloud.githubusercontent.com/assets/26387044/26012387/f75dbc5a-3719-11e7-820e-0210f547e83d.png>

is there something different in the management system that has to be done?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/omnitekinc/AERA_MSS_Clients/issues/136>, or mute the
thread

**Comment by sagarjagdish** [comment]
@omnitekinc  : We have restore backup of live database on stage before that action. You can see this action on 12th MAY 2017 at 01:05 PM and we restored database at your night nearly 12th MAY 2017 at 03:00 AM.

So all those entry before 12th MAY 2017 will be reflect on stage. 

Please let me know if any confusion.

**Comment by kbt1** [comment]
looks corrected.
