### ISSUE TITLE
Monthly Report - Membership comparison 

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#155]
numbers are still off and i am not sure why
see attached.

[Membership comparison report - new and old.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1022892/Membership.comparison.report.-.new.and.old.xlsx)

I am not sure if you dont understand how these numbers should be pulled?
I ran the Prosis comparison previously and it seemed good, i ran it today and its off.
I get good numbers through the Export tab.

**Comment by sagarjagdish** [comment]
@omnitekinc  : I have looked into this and found below things.

We are depending on Dues Transaction Start and End date => Reason : When you go at past 2016 May and lookup for the active user in May 2016 then it will give you prefect result as all those activation entry in dues transaction.  If we depends on current status only than its not work proper for the past year or month. 

1) It's only because we still have 82 member active in May-2017 but not exist in dues transaction. see attached file.
[dues_transaction_not_found.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1010665/dues_transaction_not_found.xlsx)

2) there 3 Member# having no class Id, see below list for those member.
915
23219
35925

3) I have exported Monthly comparison report and it's shows me 1867 members for May-2017.

![image_66](https://cloud.githubusercontent.com/assets/7322922/26410752/c96e76e8-40c1-11e7-811c-d5c8a7e778ed.png)

Question :
1) When we export report for 2017 then it means 2017 Finical Year of 2017 or Year 2017.
2) as per current export screen we are showing only start date and Forward as end date. So when we add 05/23/2017 we are exporting all future date which available in system, is that correct?
![image](https://cloud.githubusercontent.com/assets/7322922/26410921/34093d9e-40c2-11e7-9fcd-fef4b94d046f.png)

Can we have Short Call on this to be clear? Please let me know when we can meet.

**Comment by kbt1** [comment]
1. I will pull May Payments I processed for monthly payments today.

2. May need another function added to my reports  so all I have to do is enter a date and it pulls the numbers for Active Members from that date forward with the same breakdown. So when we have weekly meetings, I can enter for example 5/24/17 and get just counts as of that date forward for the categories.
I also need the same for Prosis Pro (# of Companies), enter a date and get a count for Prosis Pro total user count, Prosis Pro Web Users that have logins, Prosis Pro Desktop count for registered users and Prosis Pro Desk top and Web Users.  Example: as of 5/24/17 Prosis Total users: 1359, Prosis Pro Web: 1200, Prosis Pro Desktop: 85, Prosis Pro Desktop and Web: 60

3. I have taken care of the classes for the 3 members. Id#915, that is us, we dont count that in any counts.

We will have a meeting Thursday and go over this and see if we can get this all resolved and make sure I am explaining this correctly.

**Comment by omnitekinc** [comment]
@sagarjagdish AERA  Finical Year is July 1st - June 30th. 
I discussed the report with Karen, I will send you a separate email to explain.

**Comment by sagarjagdish** [comment]
We have created new report and uploaded on stage. Please see below image and excel file for for the reference.

![image](https://cloud.githubusercontent.com/assets/7322922/26452085/36b81bd6-417c-11e7-974b-59401f299961.png)

[MembershipQuickMembershipCountReport-5900.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1029080/MembershipQuickMembershipCountReport-5900.xlsx)

**Comment by kbt1** [comment]
For Membership - can you take out Prospects.  Correct Spelling for Associate Members, not Association.
For Prosis Pro - Break down as follows:

Prosis Pro Total User Count: total # of companies for each count.
Prosis Pro Web User Count: 
Prosis Pro Desktop User Count:
Prosis Pro Web and Desktop User Count:
Current 30 Day Trials:

Domestic and International and Annually and Monthly are good.

**Comment by kbt1** [comment]
Update: 
Membership Counts is getting better:
![image](https://cloud.githubusercontent.com/assets/26387044/26502481/8dcb34cc-4202-11e7-9744-5fb091cab42b.png)
Prosis Counts: count is pretty on target but the breakdown needs to be like this:
![image](https://cloud.githubusercontent.com/assets/26387044/26502910/390a1730-4204-11e7-92e9-5098932972d4.png)

keep the domestic and international counts and annual and monthly counts as is.

**Comment by kbt1** [comment]
Comparison reports for Membership and Prosis both seem off still.
Stella, we can talk about this and try to figure out what is going on.

**Comment by omnitekinc** [comment]
Let's discuss tomorrow morning. I will look into it today as well to figure out the details.

**Comment by kbt1** [comment]
here is the spreadsheet for each as of May 31st. 
[Karen Membership Comparison by Month.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1052757/Karen.Membership.Comparison.by.Month.xlsx)
[Karen  PROSIS Comparison by Month for Stella.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1052758/Karen.PROSIS.Comparison.by.Month.for.Stella.xlsx)
basically the counts are the totals for month end. So once I run May 31st, the report should not change until I run June 30th totals and so on. When I run June 30th, May counts do not change. when i run July, June counts do not change. It should all be according to expiration date. So for May 31st report, the data was pulled for Members and Prosis users who have expiration date of 5/31/17 and forward.
So for June month end, the count for June would be expiration date of 6/30/17 and forward.

**Comment by omnitekinc** [comment]
Thanks Karen, will look into this

**Comment by sagarjagdish** [comment]
We have looked into this issue and found one pending query that pending to execute on production as it's most recent change. We have verified report after executing that query and still found difference more than 100 users. Please see below for the explanation.

1) Exported report for 30th JUN and Forward  
[MembershipComparisonReport-5900.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1055057/MembershipComparisonReport-5900.xlsx)
Count is 1826

2) 98 member active till 30th June but not exist in dues transaction screen. So those members do not consider in the report.
[Comparison calculation for June 2017.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1055069/Comparison.calculation.for.June.2017.xlsx)

and that's why we have implemented Quick Membership / Prosis Pro count report to export all members without dues check. I hope all of us remember that discussion.

**Comment by kbt1** [comment]
Stella
we may need to re figure how this is pulled.
we can talk about it in the meeting. i may have to just keep a manual spreadsheet like i have been.
These reports have been pulled according to expiration dates. Not by dues transactions or payments.
The totals are pulled the last day of the month and do not include members that expired the 1st of that month. 
[Membership and Prosis Comparison Reports Old vs New.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1055355/Membership.and.Prosis.Comparison.Reports.Old.vs.New.pdf)

**Comment by omnitekinc** [comment]
@kbt1 Hi Karen, I talked to Sagar about the report, you are correct, we are using the Due Transaction date instead of the expiration date. If you are only generating a monthly report to see how many active members, expiration date would make sense, but if you are generating annual reports, and if we use expiration dates, then the number will not be accurate because the expiration date changes over time. I think in this case you just need a monthly report, please let me know your thoughts.

**Comment by kbt1** [comment]
Yes, its is an ongoing Monthly Report. 

CAN YOU CALL ME, Steve and I have a couple questions.

**Comment by omnitekinc** [comment]
@sagarjagdish 
Please go ahead and use the expiration date for this report and see if we can get closer to the number.

**Comment by sagarjagdish** [comment]
@omnitekinc : I am working on that and will send you update asap.

**Comment by sagarjagdish** [comment]
I have changed logic with the expiration date  of member and exported report for the membership for with 05/01/2017. Please find attached file for the exported report and it's look like it's much closer to old one.
 
![image](https://user-images.githubusercontent.com/7322922/27002914-623a2872-4e0a-11e7-8bde-a7baa2a5f86a.png)

[MembershipComparisonReport-5900 (9).xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1065841/MembershipComparisonReport-5900.9.xlsx)

**Comment by kbt1** [comment]
Stella
Member counts are good. 
Steve and I need to discuss the Desktop and Desktop and Web user counts.
They still seem off. Once we get closer, we can close this.

**Comment by sagarjagdish** [comment]
@kbt1 : Please find attached file for list of member which we counting under Desktop and Desktop and Web user. Please verify and let us know if we missed or considering additional member.
[ProsisProQuickMembershipCountReport-5900.xlsx](https://github.com/omnitekinc/AERA_MSS_Clients/files/1101035/ProsisProQuickMembershipCountReport-5900.xlsx)

**Comment by kbt1** [comment]
looks good.
