### ISSUE TITLE
Emailing invoices

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#214]
I am still getting this error on other records
ID#41730 expired, tried to email invoice and got error
![image](https://user-images.githubusercontent.com/26387044/27959414-f6cdf44a-62ec-11e7-97cc-fdd05c0e4592.png)
there is an email in their record
![image](https://user-images.githubusercontent.com/26387044/27959438-0680d04c-62ed-11e7-99c3-772ce4fc56a6.png)

**Comment by sagarjagdish** [comment]
@kbt1  :

It's only because member expired in 2014 and system not allow to export that much old expired member based on below requirement. Please refer below requirement for that check. If you want to send invoice then you just need to update expiry date with range to 90 days. Please let me know if any change require in this implementation.

https://github.com/omnitekinc/AERA_MSS_Clients/issues/186#issuecomment-306820485
https://github.com/omnitekinc/AERA_MSS_Clients/issues/86#issuecomment-298397673

**Comment by kbt1** [comment]
thats right, thank you
