### ISSUE TITLE
Printing invoices  - URGENT HELP REQUESTED

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#216]
something keeps getting changed, everything was printing good and now I noticed they arent.
some of these companies have membership AND prosis due and membership ONLY PRINTED.

if membership and prosis expire 90 days apart from each other, they BOTH print on the invoices whether printing or emailing.

![image](https://user-images.githubusercontent.com/26387044/27966745-ff475e22-6305-11e7-8e2d-efd76d330657.png)

**Comment by kbt1** [comment]
logged out and logged in and it fixed the issue. this should not be.

**Comment by sagarjagdish** [comment]
@kbt1 :

We have looked into this issue and it's working file. Please find attached pdf file which I exported by selection same member which you provided in your comment. We notice like out of 16 member it's exporting 13 member in print and 3 member not printed because of below reason.

1536 - monthly member, ProsisPro no account
1844 - monthly member, ProsisPro annually but it will expire on 01/01/2018
2176 - monthly member, ProsisPro annually but expired on 10/29/2016

[Invoices_not_printing_Prosis_due.pdf](https://github.com/omnitekinc/AERA_MSS_Clients/files/1134573/Invoices_not_printing_Prosis_due.pdf)

**Comment by kbt1** [comment]
once i logged out and logged back in, all the invoices pulled correctly.
i ran a first batch and noticed it was only membership and did not include Prosis.
seems to be fine now.
