### ISSUE TITLE
Export Data - Report

### ISSUE THREAD

**Issue by amandagoyette** [omnitekinc/AERA_MSS_Clients#43]
A few edits to the membership report I pulled (bottom row is mbr#44226 and what I used for reference):

1. Should say Expires in 15 Days instead of Expired in 15 Days
![image](https://cloud.githubusercontent.com/assets/26386841/24169448/a98cdda4-0e4b-11e7-9e8c-14950bf6c93d.png)

2. Additional Contacts are pulling primary phone # instead of the appropriate one for that contact: 
![image](https://cloud.githubusercontent.com/assets/26386841/24169523/e9ec8e8a-0e4b-11e7-8a46-4a308c9c832c.png)
![image](https://cloud.githubusercontent.com/assets/26386841/24169542/f7ceb19a-0e4b-11e7-92bc-ea8a2a316004.png)

**Comment by amandagoyette** [comment]
Also Address information doesn't pull into reports 
![image](https://cloud.githubusercontent.com/assets/26386841/24169755/9e6e1770-0e4c-11e7-8db1-86c479006eb8.png)

**Comment by sagarjagdish** [comment]
+++++++++++++
Should say Expires in 15 Days instead of Expired in 15 Days
+++++++++++++
**updated text as suggested.**

+++++++++++++
Additional Contacts are pulling primary phone # instead of the appropriate one for that contact:
+++++++++++++
**resolved this issue.**

+++++++++++++
Also Address information doesn't pull into reports
+++++++++++++
**resolved this issue.**

**Comment by amandagoyette** [comment]
appears to be fixed.  thanks!
