### ISSUE TITLE
Membership - adding a new member

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#76]
when you add a new member, it should not assign an expiration date until dues is posted.
Also, all exp dates are always the 1st of the month.
So once added to membership, when i enter dues and post, will it add another year to exp date?

![image](https://cloud.githubusercontent.com/assets/26387044/24477452/ac5d7730-149c-11e7-96f1-99786741c9c3.png)

**Comment by sagarjagdish** [comment]
when you add a new member, it should not assign an expiration date until dues is posted.
=> done, expiration date not set until dues is posted.

Also, all exp dates are always the 1st of the month.
=> done, inside dues screen when you add member# it's shows 01st of the month as expiration date.

So once added to membership, when i enter dues and post, will it add another year to exp date?
=>It's will add 1 year to exp date. 
let's take example. I have created one member by today 5th-APR-2017 and go for dues screen to add amount. it will shows me new exp date is 01st-Apr-2018.

**Comment by kbt1** [comment]
Stella
I added member #44230
Posted dues transaction
 - there is no "Start date"
 - it says 11 month subscription

not sure this is right? all new subscriptions should be 12 months and i guess start date is the same as joined date?????

![image](https://cloud.githubusercontent.com/assets/26387044/24802257/e66be53e-1b6c-11e7-8197-efb7811fb830.png)

**Comment by omnitekinc** [comment]
Sagar, can you please look into this.

**Comment by kbt1** [comment]
looks like this is good now. However, i added this record and edited it and it has Dave Hagen instead of Karen Tendering???
![image](https://cloud.githubusercontent.com/assets/26387044/25625763/04ca69e6-2f23-11e7-9240-2c421df85202.png)

**Comment by sagarjagdish** [comment]
not sure this is right? all new subscriptions should be 12 months and i guess start date is the same as joined date?????
=> updated logic as suggested by Stella in yesterday reply.

looks like this is good now. However, i added this record and edited it and it has Dave Hagen instead of Karen Tendering???
=> I did login with Steve Fox and updated same Member and updated by changed to "Steve Fox". Please refer below image.

![image](https://cloud.githubusercontent.com/assets/7322922/25743085/368c1bc0-31b0-11e7-95e4-c746f8469579.png)

**Comment by kbt1** [comment]
looks like it good now.
