### ISSUE TITLE
tech que

### ISSUE THREAD

**Issue by kbt1** [omnitekinc/AERA_MSS_Clients#95]
Under Membership tab when I pull up a member and click on Tech Que to create a call, i get this error:

![image](https://cloud.githubusercontent.com/assets/26387044/24968664/86216fc2-1f73-11e7-9f9f-1068c2871a6c.png)

"You have no rights to access this page"   all staff should be able to add a call.

**Comment by sagarjagdish** [comment]
It's only because you have open access to this scree. I have changed to Full and now you can add/edit/delete inside Tech Call. Also your name started to show under "Assigned" dropdown list so you can select your name as Assigned when you create call. All the member who having Full access of Tech Call will be listed under Assigned drop down list. 

Please let me know if any change required in this.

![image](https://cloud.githubusercontent.com/assets/7322922/25001656/1ece5f96-2064-11e7-8eb2-34261b5fb930.png)

**Comment by kbt1** [comment]
works now.
